### ISSUE TITLE
Feedback

### ISSUE THREAD

**Issue by zjedwin** [DustySounds/Codecademy---Coding-with-Python-Capstone---Tome-Rater#1]
Thanks for your submission. What follows are mostly stylistic recommendations. The first comment, however, discusses a point which will effect the correctness of your program on reasonable inputs.

### `create_book` method in `TomeRater`
Handling the error of a repeated ISBN by defining book to be a string:
```python
book = "Book entry of {t} failed due to duplicated ISBN".format(t = title)
```
is not recommended. As written, this method will return either a `Book` object or a string object but no explicit handling of the exceptional case is done. So a legitimate agent running this program will have to read the print statement before utilizing the return value; which is unlikely. A better result is to throw an exception in the case of a repeated ISBN.

The same goes for your `create_novel` and `create_non_fiction` methods.

### `add_user` method in `TomeRater`
Your check to validate an email address is not very robust. For example, `@.com` and `@   .com.edu.org` are legitimate emails in your implementation. To write a more robust version, I recommend exploring regular expressions in Python.

### A comment on writing helper functions
Notice that the methods, `most_read_book`, `highest_rated_book`, and `most_positive_user` have implementations which are copy/paste of one another with minor changes. Whenever you have a circumstance where a core functionality being performed is the same across many parts of your code, it is often a good idea to think of abstracting that core functionality out into a separate function. You can then call that function multiple times instead of copying code multiple times. The same can be said about `get_n_most_read_books` and `get_n_most_prolific_readers`.

**Comment by DustySounds** [comment]
Recommendations have been implemented.
