### ISSUE TITLE
Score

### ISSUE THREAD

**Issue by zjedwin** [DustySounds/Codecademy---Coding-with-Python-Capstone---Tome-Rater#2]
### Criteria 1: Valid Python Code
* _Score Level:_ 4
* _Comment(s):_ The code that you provide runs without errors.
 
### Criteria 2: Implementation of Project Requirements
* _Score Level:_ 4
* _Comment(s):_ You provide correct implementations (with care taken for corner cases), of the methods and classes required by the assignment.
 
### Criteria 3: Software Architecture
* _Score Level:_ 3
* _Comment(s):_ Code is separated into distinct classes and methods, each which are invoked for their own purposes. The only drawbacks are the points I make in my feedback on (1) your `create...` methods returning either a `Book` or string without handling exceptions and (2) your `TomeRater` class about repeated code.
 
### Criteria 4: Uses Python Language Features
* _Score Level:_ 3
* _Comment(s):_ Although you could have made more use of Python built-in functionality to accomplish your tasks, in validating emails, for example, you make enough use of Python built-in functionality to aid in accomplishing your tasks.
 
### Overall Score: 14/16
Thank you for your submission. I've given feedback on some aspects of your code [here](https://github.com/DustySounds/Codecademy---Coding-with-Python-Capstone---Tome-Rater/issues/1). I hope that you find in it something useful.

**Comment by DustySounds** [comment]
Thank you @zjedwin for your feedback. I've gone ahead and made the changes you recommended. Just for the record, this was and introductory python intensive course and regular expressions were not covered, so I was a little sad to lose another point there after your initial grading. But anyway thank you for the recommendations as I learned more from implementing your suggestions. All the best.

**Comment by zjedwin** [comment]
@DustySounds Thanks for your comment. I would recommend this chapter as a good resource for the basic use of regular expressions in Python. Overall, the book is helpful (and free).

**Comment by DustySounds** [comment]
@zjedwin Which book do you mean? I don't see a link or title in your last message.

**Comment by zjedwin** [comment]
@DustySounds The link is [here](https://automatetheboringstuff.com/chapter7/). I had the tab open but didn't embed the link.

**Comment by DustySounds** [comment]
Great, thank you!
